### ISSUE TITLE
Adjusted Total Downloads are Unstable

### ISSUE THREAD

**Issue by dcgerard** [tylermorganwall/adjustedcranlogs#5]
Hey there! I was interested in your package, but when I ran the example code on my package twice I got very different numbers of adjusted total downloads:

``` r
library(adjustedcranlogs)
library(ggplot2)
library(dplyr)
library(lubridate)

set.seed(1)
mypkgdownloads <- adj_cran_downloads("updog", 
                                     from = "2018-05-01",
                                     to = "2019-07-11")

mypkgdownloads2 <- adj_cran_downloads("updog", 
                                      from = "2018-05-01",
                                      to = "2019-07-11")

mypkgdownloads$adjusted_total_downloads[nrow(mypkgdownloads)]
mypkgdownloads2$adjusted_total_downloads[nrow(mypkgdownloads2)]
```

In the first case, I got 2082, in the second I got 1503.

Could this indicate a need to change some of the defaults?

Thanks!
David

**Comment by grayknight2** [comment]
Same issue. Running twice the same code I get different results..

**Comment by tylermorganwall** [comment]
There's always going to be some stochasticity since the minimum count is taken using a random sample of packages, however, I've switched the default method to use the minimum number of downloads during each day (rather than the 0.05 quantile) which should help reduce the variance.

The two values get running your example with the latest update is 2490 and 2507.
